# Testing pVQD original qiskit code

In [21]:
import numpy as np
large_width = 400
np.set_printoptions(linewidth=large_width)

In [1]:
	from qiskit.opflow          import Z, I


In [2]:
def projector_zero(n_qubits):
	# This function create the global projector |00...0><00...0|
	from qiskit.opflow            import Z, I
	
	prj_list = [0.5*(I+Z) for i in range(n_qubits)]
	prj = prj_list[0]
	
	for a in range(1,len(prj_list)):
		prj = prj^prj_list[a]
	
	return prj

def projector_zero_local(n_qubits):
	# This function creates the local version of the cost function 
	# proposed by Cerezo et al: https://www.nature.com/articles/s41467-021-21728-w
	from qiskit.opflow          import Z, I
	
	tot_prj = 0
	
	for k in range(n_qubits):
		prj_list = [I for i in range(n_qubits)]
		prj_list[k] = 0.5*(I+Z)
		prj = prj_list[0]
	
		for a in range(1,len(prj_list)):
			prj = prj^prj_list[a]
	
		#print(prj)
	
		tot_prj += prj
	
	tot_prj = (1/n_qubits)*tot_prj
	
	return tot_prj

In [28]:
[0.5*(I+Z).to_matrix() for i in range(3)]

[array([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]),
 array([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]),
 array([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]])]

In [30]:
prj_list = [0.5*(I+Z) for i in range(3)]
prj = prj_list[0]

In [35]:
(prj^prj_list[1]).to_matrix()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [25]:
projector_zero(3).to_matrix().astype(float)

/Users/adam/miniconda3/envs/pvqd/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
projector_zero_local(3).to_matrix()

array([[1.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.66666667+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.66666667+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.33333333+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.66666667+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.33333333+0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j, 0.33333333+0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0

In [24]:
projector_zero_local(3).to_matrix().astype(float)

/Users/adam/miniconda3/envs/pvqd/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([[1.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.66666667, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.33333333, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.66666667, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ]])

In [42]:
import numpy as np
#import matplotlib.pyplot as plt


from qiskit.quantum_info 			  import Pauli
from qiskit.opflow      			  import PauliOp, SummedOp

def generate_pauli(idx_x,idx_z,n):
	'''
	Args:
		n (integer)
		idx (list)
	Returns:
		tensor product of Pauli operators acting on qubits in idx
	'''

	xmask = [0]*n
	zmask = [0]*n
	for i in idx_x : xmask[i] = 1
	for i in idx_z : zmask[i] = 1

	a_x = np.asarray(xmask,dtype =np.bool)
	a_z = np.asarray(zmask,dtype =np.bool)

	return Pauli(a_z,a_x)


def generate_ising_pbc(n_spins,coup,field):
	'''
	Args:
		n_spins (integer)
		coup    (float)
		field   (float)
		
	Returns:
		Hamiltonian of Ising model with ZZ interaction a X transverse field, pbc
	'''

	int_list = []
	field_list = []

	int_list.append(generate_pauli([],[0,n_spins-1],n_spins))

	if(n_spins>2):
		for i in range(n_spins-1):
			int_list.append(generate_pauli([],[i,i+1],n_spins))

	for i in range(n_spins):
		field_list.append(generate_pauli([i],[],n_spins))

	int_coeff = [coup]*len(int_list)
	field_coeff = [field]*len(field_list)

	H = PauliOp(int_list[0],int_coeff[0])

	for i in range(1,len(int_list)):
		H = H + PauliOp(int_list[i],int_coeff[i])

	for i in range(len(field_list)):
		H = H + PauliOp(field_list[i],field_coeff[i])

	return H, int_list, field_list
	

def generate_ising(n_spins,coup,field):
	'''
	Args:
		n_spins (integer)
		coup    (float)
		field   (float)
		
	Returns:
		Hamiltonian of Ising model with ZZ interaction a X transverse field
	'''

	int_list = []
	field_list = []


	for i in range(n_spins-1):
		int_list.append(generate_pauli([],[i,i+1],n_spins))

	for i in range(n_spins):
		field_list.append(generate_pauli([i],[],n_spins))

	int_coeff = [coup]*len(int_list)
	field_coeff = [field]*len(field_list)

	H = PauliOp(int_list[0],int_coeff[0])

	for i in range(1,len(int_list)):
		H = H + PauliOp(int_list[i],int_coeff[i])

	for i in range(len(field_list)):
		H = H + PauliOp(field_list[i],field_coeff[i])

	return H, int_list, field_list



In [43]:
h, i, f = generate_ising(3, .25, 1)

/Users/adam/miniconda3/envs/pvqd/lib/python3.7/site-packages/ipykernel_launcher.py:22: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
/Users/adam/miniconda3/envs/pvqd/lib/python3.7/site-packages/ipykernel_launcher.py:23: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


In [44]:
i

[Pauli('IZZ'), Pauli('ZZI')]

In [45]:
f

[Pauli('IIX'), Pauli('IXI'), Pauli('XII')]

In [46]:
h, i, f = generate_ising_pbc(3, .25, 1)

/Users/adam/miniconda3/envs/pvqd/lib/python3.7/site-packages/ipykernel_launcher.py:22: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
/Users/adam/miniconda3/envs/pvqd/lib/python3.7/site-packages/ipykernel_launcher.py:23: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


In [47]:
h

PauliSumOp(SparsePauliOp([[False, False, False,  True, False,  True],
               [False, False, False,  True,  True, False],
               [False, False, False, False,  True,  True],
               [ True, False, False, False, False, False],
               [False,  True, False, False, False, False],
               [False, False,  True, False, False, False]],
              coeffs=[0.25+0.j, 0.25+0.j, 0.25+0.j, 1.  +0.j, 1.  +0.j, 1.  +0.j]), coeff=1.0)

In [48]:
i

[Pauli('ZIZ'), Pauli('IZZ'), Pauli('ZZI')]

In [49]:
f

[Pauli('IIX'), Pauli('IXI'), Pauli('XII')]